"""
WipeX - PDF reports (ReportLab): erasure certificate, recovery report and file-erasure
report, each followed by a draft annexure in the style of a certificate under
Section 63 of the Bharatiya Sakshya Adhiniyam, 2023 (electronic records).
The annexure is a template to be completed and signed by the responsible person; WipeX
does not claim that the generated document is legally sufficient on its own.
"""

import hashlib
import io
import time
from typing import Any, Dict, List, Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.graphics.barcode.qr import QrCodeWidget
from reportlab.graphics.shapes import Drawing
from reportlab.lib.units import mm
from reportlab.platypus import (KeepTogether, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table,
                                TableStyle)

from crypto_signer import CryptoSigner

INK = colors.HexColor("#15212b")
ACCENT = colors.HexColor("#0d6e6e")
MUTED = colors.HexColor("#5b6670")
LINE = colors.HexColor("#d6dbdf")

_ss = getSampleStyleSheet()
H1 = ParagraphStyle("h1", parent=_ss["Heading1"], fontName="Helvetica-Bold", fontSize=16, textColor=INK, spaceAfter=4)
H2 = ParagraphStyle("h2", parent=_ss["Heading2"], fontName="Helvetica-Bold", fontSize=11.5, textColor=ACCENT, spaceBefore=10, spaceAfter=4)
BODY = ParagraphStyle("body", parent=_ss["BodyText"], fontName="Helvetica", fontSize=9.5, leading=13, textColor=INK, alignment=TA_LEFT)
SMALL = ParagraphStyle("small", parent=BODY, fontSize=8, leading=10.5, textColor=MUTED)
MONO = ParagraphStyle("mono", parent=BODY, fontName="Courier", fontSize=7.8, leading=10)


def _kv(rows: List[List[Any]], widths=(55 * mm, 115 * mm)) -> Table:
    data = [[Paragraph(f"<b>{k}</b>", BODY), v if not isinstance(v, str) else Paragraph(v, BODY)] for k, v in rows]
    t = Table(data, colWidths=widths)
    t.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"), ("LINEBELOW", (0, 0), (-1, -1), 0.4, LINE),
                           ("TOPPADDING", (0, 0), (-1, -1), 3), ("BOTTOMPADDING", (0, 0), (-1, -1), 3)]))
    return t


def _grid(header: List[str], rows: List[List[Any]], widths) -> Table:
    data = [[Paragraph(f"<b>{h}</b>", SMALL) for h in header]] + \
           [[c if not isinstance(c, str) else Paragraph(c, SMALL) for c in r] for r in rows]
    t = Table(data, colWidths=widths, repeatRows=1)
    t.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eef3f3")),
                           ("LINEBELOW", (0, 0), (-1, -1), 0.4, LINE), ("VALIGN", (0, 0), (-1, -1), "TOP"),
                           ("TOPPADDING", (0, 0), (-1, -1), 2), ("BOTTOMPADDING", (0, 0), (-1, -1), 2)]))
    return t


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(MUTED)
    canvas.drawString(18 * mm, 10 * mm, "WipeX — integrated secure erasure and forensic recovery · SIH26149")
    canvas.drawRightString(192 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _build(story: List[Any], title: str) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm,
                            bottomMargin=18 * mm, title=title, author="WipeX")
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


def _annexure(record_desc: str, device_desc: str, digest: str, produced_by: str) -> List[Any]:
    key_fp = hashlib.sha256(CryptoSigner.get_public_key_pem().encode()).hexdigest()[:32]
    return [
        PageBreak(),
        Paragraph("Annexure — Draft certificate for an electronic record", H1),
        Paragraph("Prepared in the form contemplated by Section 63 of the Bharatiya Sakshya Adhiniyam, 2023. "
                  "This is a draft generated by WipeX; it must be reviewed, completed and signed by the person "
                  "responsible for the device or process, and (where required) by an expert.", SMALL),
        Spacer(1, 6),
        Paragraph("Part A — To be filled by the party", H2),
        _kv([
            ["Electronic record", record_desc],
            ["Produced from", device_desc],
            ["Produced by (computer / software)", "WipeX workstation, operated by " + (produced_by or "—")],
            ["Hash value (SHA-256)", Paragraph(digest, MONO)],
            ["Signing key fingerprint", Paragraph(key_fp, MONO)],
        ]),
        Spacer(1, 6),
        Paragraph("I state that the electronic record identified above was produced by the computer / software named, "
                  "which was operating properly during the relevant period, and that the information was stored and "
                  "processed in the ordinary course of its use. The hash value above identifies the record exactly.", BODY),
        Spacer(1, 16),
        _kv([["Name", " "], ["Designation", " "], ["Date and place", " "], ["Signature", " "]]),
        Paragraph("Part B — Expert (where applicable)", H2),
        Paragraph("To be completed by the examiner of electronic evidence, confirming the hash value and the "
                  "integrity of the record.", SMALL),
        Spacer(1, 10),
        _kv([["Name", " "], ["Designation / notification", " "], ["Date and place", " "], ["Signature", " "]]),
    ]


def _describe_check(c: Dict[str, Any]) -> str:
    if c.get("name") == "Pattern read-back":
        text = (f"Expected {c.get('expected')}; coverage {c.get('coverage')}; "
                f"{c.get('mismatchedRegions', 0)} mismatched region(s)")
        if c.get("unchangedBlocks"):
            text += f"; {c['unchangedBlocks']} block(s) still hold old content"
        if c.get("readErrors"):
            text += f"; {c['readErrors']} read error(s)"
        return text
    if c.get("name") == "Canary blocks":
        return f"{c.get('planted')} marker blocks planted before erasure; {c.get('recovered')} found afterwards"
    if c.get("name") == "Recovery attempt (M3)":
        return c.get("reason") if c.get("skipped") else c.get("detail", "")
    return ", ".join(f"{k}: {v}" for k, v in c.items() if k not in ("name", "passed"))


# ── Erasure certificate ──────────────────────────────────────────────────────

def _qr(text: str, size: float = 30 * mm) -> Drawing:
    widget = QrCodeWidget(text)
    x0, y0, x1, y1 = widget.getBounds()
    drawing = Drawing(size, size, transform=[size / (x1 - x0), 0, 0, size / (y1 - y0), 0, 0])
    drawing.add(widget)
    return drawing


def certificate_pdf(cert: Dict[str, Any], verify_url: Optional[str] = None) -> bytes:
    v = cert.get("verification") or {}
    ok = cert.get("trustScore") == "GREEN"
    story: List[Any] = [
        Paragraph("Certificate of Data Sanitization", H1),
        Paragraph(f"Certificate ID <b>{cert['certificateId']}</b> · issued {cert['issueDate']}", BODY),
        Spacer(1, 6),
        Table([[Paragraph(f"<b>{'PASS' if ok else 'NOT SANITIZED'}</b> — {cert.get('cleanedStatus') or ''}", BODY)]],
              colWidths=[174 * mm],
              style=TableStyle([("BOX", (0, 0), (-1, -1), 0.8, ACCENT if ok else colors.HexColor("#a8261d")),
                                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#e6f3f1" if ok else "#fbe8e6")),
                                ("TOPPADDING", (0, 0), (-1, -1), 6), ("BOTTOMPADDING", (0, 0), (-1, -1), 6)])),
        Paragraph("Device", H2),
        _kv([["Model", cert.get("deviceModel") or "—"], ["Serial number", cert.get("serialNumber") or "—"],
             ["Media type", cert.get("storageType") or "—"],
             ["Capacity", f"{cert.get('capacityBytes') or 0:,} bytes"]]),
        Paragraph("Sanitization", H2),
        _kv([["Method", cert.get("standard") or "—"], ["NIST SP 800-88 category", cert.get("category") or "—"],
             ["Passes", ", ".join(cert.get("passes") or []) or "Device firmware command"],
             ["Operator", cert.get("operator") or "—"], ["Approver (two-person rule)", cert.get("approver") or "—"],
             ["Disposition", cert.get("trustScoreLabel") or "—"]]),
        Paragraph("Verification", H2),
    ]
    rows = []
    for c in v.get("checks", []):
        detail = _describe_check(c)
        rows.append([c.get("name", ""), "Pass" if c.get("passed") else ("Skipped" if c.get("passed") is None else "Fail"), detail])
    story.append(_grid(["Check", "Result", "Evidence"], rows, [45 * mm, 18 * mm, 111 * mm]))
    story += [
        Spacer(1, 4),
        Paragraph(f"Overall verdict: <b>{v.get('verdict', '—')}</b>. Mean Shannon entropy of samples: {v.get('meanEntropy')}. "
                  "Entropy is informational only; the verdict comes from pattern read-back and the recovery attempt.", SMALL),
        Paragraph("Integrity", H2),
        _kv([["SHA-256 of signed content", Paragraph(cert["sha256Digest"], MONO)],
             ["Signature", Paragraph(cert.get("signatureAlgorithm", "ECDSA P-256"), BODY)],
             ["Signature status", "Valid" if cert.get("isValid") else "INVALID — do not rely on this certificate"]]),
        Paragraph("Verify at any time in WipeX → Verify certificate, using the certificate ID or serial number.", SMALL),
        Table([[_qr(verify_url or cert["certificateId"]),
                Paragraph("Scan to open this certificate in WipeX Verify on the issuing workstation.<br/>"
                          f"Certificate ID: {cert['certificateId']}", SMALL)]],
              colWidths=[34 * mm, 140 * mm], style=TableStyle([("VALIGN", (0, 0), (-1, -1), "MIDDLE")])),
    ]
    story += _annexure(f"Certificate of data sanitization {cert['certificateId']}",
                       f"{cert.get('deviceModel')} (serial {cert.get('serialNumber')})",
                       cert["sha256Digest"], cert.get("operator") or "")
    return _build(story, f"WipeX certificate {cert['certificateId']}")


# ── Recovery report ──────────────────────────────────────────────────────────

def recovery_pdf(job: Dict[str, Any], case: Optional[Dict[str, Any]] = None, evidence: Optional[Dict[str, Any]] = None) -> bytes:
    res = job.get("result") or {}
    fs = res.get("filesystem") or {}
    carving = res.get("carving") or {}
    story: List[Any] = [
        Paragraph("Forensic Recovery Report", H1),
        Paragraph(f"Job {job['id']} · {job.get('finished_at') or job.get('created_at')}", BODY),
        Paragraph("Case and source", H2),
        _kv([["Case", f"{case['id']} — {case['title']}" if case else "—"],
             ["Investigator", case["investigator"] if case else "—"],
             ["Source", res.get("source", "—")],
             ["Evidence item", f"{evidence['id']} ({evidence['label']})" if evidence else "—"],
             ["Acquisition SHA-256", Paragraph(evidence["sha256"], MONO) if evidence else "—"],
             ["Summary", res.get("summary", "—")]]),
        Paragraph("Techniques", H2),
        Paragraph("1. File-system analysis with The Sleuth Kit: directory entries marked deleted are listed with their "
                  "metadata and their clusters are read back. 2. Signature and structure carving over the whole source: "
                  "each candidate is parsed (JPEG markers, PNG CRCs, PDF cross-reference, ZIP central directory, GIF blocks, "
                  "SQLite header). 3. Bifragment gap carving for fragmented PNG and ZIP files, accepted only when the "
                  "format's own checksums validate. Source media is opened read-only.", BODY),
    ]
    volumes = fs.get("volumes") or []
    if volumes:
        story += [Paragraph("File systems found", H2),
                  _grid(["#", "Type", "Offset", "Description"],
                        [[str(v["index"]), v["fsType"], f"{v['offset']:,}", v["description"]] for v in volumes],
                        [10 * mm, 30 * mm, 35 * mm, 99 * mm])]
    deleted = [e for e in fs.get("entries", []) if e.get("deleted") and not e.get("isDir")]
    if deleted:
        story += [Paragraph(f"Deleted entries recovered from the file system ({len(deleted)})", H2),
                  _grid(["Path", "Size", "Modified", "Content", "SHA-256"],
                        [[e["path"], f"{e['size']:,}", e.get("modified") or "—", e.get("contentStatus", "—"),
                          Paragraph((e.get("sha256") or "—")[:32] + "…", MONO)] for e in deleted],
                        [56 * mm, 18 * mm, 32 * mm, 18 * mm, 50 * mm])]
    files = carving.get("files") or []
    if files:
        story += [Paragraph(f"Carved files ({len(files)})", H2),
                  _grid(["ID", "Type", "Offset", "Size", "Status", "Technique", "SHA-256"],
                        [[f["id"], f["ext"], f"{f['offset']:,}", f"{f['size']:,}", f["status"], f["technique"],
                          Paragraph(f["sha256"][:24] + "…", MONO)] for f in files],
                        [12 * mm, 12 * mm, 22 * mm, 18 * mm, 16 * mm, 50 * mm, 44 * mm])]
    digest = hashlib.sha256(repr(sorted((f["sha256"] for f in files))).encode()).hexdigest()
    story += _annexure(f"Recovery report {job['id']} listing {len(files)} carved and {len(deleted)} deleted files",
                       res.get("source", "—"), evidence["sha256"] if evidence else digest,
                       case["investigator"] if case else "")
    return _build(story, f"WipeX recovery report {job['id']}")


# ── File erasure report ──────────────────────────────────────────────────────

def file_erasure_pdf(report: Dict[str, Any]) -> bytes:
    story: List[Any] = [
        Paragraph("File & Folder Erasure Report", H1),
        Paragraph(f"Job {report['jobId']} · {report['finishedAt']} · verdict <b>{report['verdict']}</b>", BODY),
        Paragraph("Summary", H2),
        _kv([["Result", report["summary"]], ["Overwrite passes", str(report["passes"])],
             ["Operator", report.get("operator") or "—"], ["Approver", report.get("approver") or "—"]]),
        Paragraph("Storage assurance", H2),
    ]
    for vol in report.get("volumes", []):
        story.append(_kv([["Volume", f"{vol['volume']} ({vol['fileSystem']}, {vol['mediaType']})"],
                          ["Assurance", vol["assurance"]], ["Advice", vol["advice"]],
                          ["Notes", " ".join(vol.get("notes", [])) or "—"]]))
    story += [Paragraph(f"Files erased ({len(report['files'])})", H2),
              _grid(["Original path", "Bytes", "Streams", "Verified"],
                    [[f["path"], f"{f['size']:,}", ", ".join(s["name"] for s in f["streams"]) or "—",
                      "Yes" if f["verified"] else "No"] for f in report["files"]],
                    [110 * mm, 22 * mm, 25 * mm, 17 * mm])]
    tc = report.get("traceCheck") or {}
    story += [Paragraph("Drive trace check", H2),
              Paragraph(tc.get("summary", "Not run"), BODY)]
    rows = [[f["folder"], f"{f.get('entries', 0)}", ", ".join(f.get("namesFound", [])) or "none",
             ", ".join(f.get("contentFound", [])) or "none"] for f in tc.get("folders", [])]
    rows += [[s["folder"], "—", "not checked", s["reason"]] for s in tc.get("skipped", [])]
    rows += [[j["volume"], "change journal", f"{j['recordsWithNames']} record(s)", "—"] for j in tc.get("journal", [])]
    if rows:
        story.append(_grid(["Folder read from the volume", "Entries", "Original names found", "Content found"],
                           rows, [84 * mm, 24 * mm, 36 * mm, 30 * mm]))
    if report.get("traces"):
        story += [Paragraph("Trace cleanup", H2),
                  _grid(["Artefact", "Result"], [[t["path"], t["result"]] for t in report["traces"]], [120 * mm, 54 * mm])]
    if report.get("failures"):
        story += [Paragraph("Failures", H2),
                  _grid(["Path", "Error"], [[f["path"], f["error"]] for f in report["failures"]], [100 * mm, 74 * mm])]
    digest = hashlib.sha256(repr(report).encode()).hexdigest()
    story += _annexure(f"File erasure report {report['jobId']}", ", ".join(v["volume"] for v in report.get("volumes", [])),
                       digest, report.get("operator") or "")
    return _build(story, f"WipeX file erasure {report['jobId']}")
